package tfimport

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/priyanshujain/infrasync/internal/providers/google"
)

type TerraformImporter interface {
	SaveImportBlock(google.Resource) error
}

func (i importer) SaveImportBlock(resource google.Resource) error {
	filePath := filepath.Join(i.outputPath, fmt.Sprintf("%s.tf", resource.Name))

	var content string
	content = "# Generated by InfraSync"
	content += generateImportBlockContent(resource)

	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write import file: %w", err)
	}

	return nil
}

func generateImportBlockContent(resource google.Resource) string {
	var content = "\n"
	content += fmt.Sprintf(`
import {
	to = %s.%s
	id = "%s"
}`, resource.Type, resource.Name, resource.ID)

	if len(resource.Dependents) > 0 {
		for _, d := range resource.Dependents {
			content += generateImportBlockContent(d)
		}
	}

	return content
}
