package tfimport

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/priyanshujain/infrasync/internal/providers/google"
)

type TerraformGenerator interface {
	SaveImportBlock(google.Resource) error
}

func (i importer) SaveImportBlock(resource google.Resource) error {
	// Create the directory for resources
	resourceDir := filepath.Join("terraform", "resources", "gcp", resource.Provider.ProjectID, resource.Service.String())
	if err := os.MkdirAll(resourceDir, 0755); err != nil {
		return fmt.Errorf("failed to create resource directory: %w", err)
	}

	// Create file named after the resource
	filePath := filepath.Join(resourceDir, fmt.Sprintf("%s.tf", resource.Name))

	// Create import block content
	var content string
	content = "# Generated by InfraSync"
	content += generateImportBlockContent(resource)

	// Write to file
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write import file: %w", err)
	}

	return nil
}

func generateImportBlockContent(resource google.Resource) string {
	var content = "\n"
	content += fmt.Sprintf(`
import {
	to = %s.%s
	id = "%s"
}`, resource.Type, resource.Name, resource.ID)

	if len(resource.Dependents) > 0 {
		for _, d := range resource.Dependents {
			content += generateImportBlockContent(d)
		}
	}

	return content
}
